### ISSUE TITLE
Question on keyid

### ISSUE THREAD

**Issue by ahmed-bacha** [flynn/go-tuf#101]
Hi guys,

I am wondering how do you generate a keyID for a given key (curiosity) ?

I found this but I did not get it: [code](https://github.com/flynn/go-tuf/blob/a98aea1463c972506e302344ebbfa30f85b74f2f/repo.go#L208)

```
role.KeyIDs = append(role.KeyIDs, pk.ID())
```

Thanks :)

**Comment by lmars** [comment]
See [here](https://github.com/flynn/go-tuf/blob/a98aea1463c972506e302344ebbfa30f85b74f2f/data/types.go#L38-L45) for the key ID generation (basically create a canonical JSON representation of the key, generate a SHA256 sum of that and return it in hex form).

**Comment by ahmed-bacha** [comment]
Perfect, thanks :)
