### ISSUE TITLE
Local metadata which does not verify should not block updates

### ISSUE THREAD

**Issue by lmars** [flynn/go-tuf#40]
If a new `root.json` is downloaded during an update (e.g. because the local one is expired), and the new `root.json` has completely different keys, then other local metadata can potentially no longer be verified in `Client.getLocalMeta`, leaving the client unable to update.

Instead of returning an error when local data does not verify, it should be invalidated and re-downloaded, possibly logging the failed verification somewhere.

**Comment by titanous** [comment]
Closed by #58.
