### ISSUE TITLE
Passphrase-protect keys

### ISSUE THREAD

**Issue by titanous** [flynn/go-tuf#5]
The `tuf` command should default to saving keys in encrypted form using a passphrase. The passphrase should be passed interactively by default with an option to pass it via an environment variable (as a very weak attempt to prevent it from leaking to observers of `ps`). An option to disable encryption (like `--insecure-plaintext-key` or similar) should be provided as well.

The encryption steps are as follows:

- Retrieve a 32 byte random salt using `crypto/rand`
- Pass the salt and passphrase to [scrypt](https://godoc.org/golang.org/x/crypto/scrypt) with the following parameters:
    - N=32768
    - r=8
    - p=1
    - length=32
- Retrieve a 24 byte random nonce using `crypto/rand`
- Encrypt the entire key JSON (in the same format that the plaintext key is stored) using [nacl/secretbox](https://godoc.org/golang.org/x/crypto/nacl/secretbox)
- Persist the salt, parameters, nonce, and ciphertext to the JSON file

The N parameter was chosen to be ~100ms of work using the default implementation on the 2.3GHz Core i7 Haswell processor in my late-2013 Apple Retina Macbook Pro (it takes 113ms).

The JSON should probably look something like this:

```json
{
  "_type": "encrypted-key",
  "kdf": {
    "name": "scrypt",
    "params": {
      "N": 32768,
      "r": 8,
      "p": 1
    },
    "salt": "<base64 encoded bytes>"
  },
  "algorithm": {
    "name": "nacl/secretbox",
    "nonce": "<base64 encoded bytes>"
  },
  "ciphertext": "<base64 encoded bytes>"
}
```

**Comment by titanous** [comment]
The encryption code now exists in the `encrypted` package, all that's remaining is modifications to the CLI.

**Comment by lmars** [comment]
So I'm thinking of having something like this in [`local_store.go`](https://github.com/flynn/go-tuf/blob/master/local_store.go):

```go
type persistedKey struct {
	Encrypted bool            `json:"encrypted"`
	Key       json.RawMessage `json:"key"`
}
```

then `Key` either gets unmarshaled directly into `*data.Key`, or is passed to `encrypted.Decrypt` and then the result unmarshaled.

To get the passphrase from the CLI to the local store, I'm thinking of adding a `passphrase` package and the second arg to [`FileSystemStore`](https://github.com/flynn/go-tuf/blob/master/local_store.go#L70) will be a `passphrase.Reader` or similar (which the CLI will set [here](https://github.com/flynn/go-tuf/blob/master/tuf/main.go#L97)), meaning the local store is responsible for the encryption / decryption, and the `Repo` always handles unencrypted keys (i.e. [here](https://github.com/flynn/go-tuf/blob/master/repo.go#L319-L351)).

Thoughts welcome on this approach before I start implementing.

**Comment by titanous** [comment]
This strategy sounds good! One thing to consider is that the encrypt/decrypt operation takes 100ms to derive the key so putting all the keys in a single encrypted blob might be better, but I haven't thought about the implications. If it's easy enough, a command to toggle encryption and change the passphrase would also be useful. Also, if there is no encrypted data, we might want to read a confirmation of the passphrase.

**Comment by lmars** [comment]
@titanous so currently CLI commands only need keys for a single role (e.g. `tuf add` needs targets keys, `tuf snapshot` needs snapshot keys etc.) so having them all in one file wouldn't really save any time.

It probably makes sense to have multiple keys for the same role in one encrypted file though as they are fetched together, so a workflow could look like this:

```
$ tuf gen-key root
No existing root keys found
Generating new root keys file
Enter passphrase:
Repeat passphrase:
Added 1 key to root keys file

$ tuf gen-key targets
No existing targets keys found
Generating new targets keys file
Enter passphrase:
Repeat passphrase:
Added 1 key to targets keys file

$ tuf gen-key targets
Existing targets keys found
Unlocking encrypted targets keys...
Enter passphrase:
Added 1 key to targets keys file

$ tuf add file.txt
Detected local targets keys, attempting to sign targets.json...
Enter passphrase:
Signed targets.json with 2 targets keys

$ tuf gen-key timestamp --insecure-plaintext
No existing timestamp keys found
Generating new timestamp keys file
Are you sure you want to store keys in plaintext? (y/n):
Added 1 key to timestamp keys file
```

For changing passphrase / disabling encryption:

```
$ tuf change-passphrase root
Enter current passphrase:
Enter new passphrase:
Repeat new passphrase:

$ tuf disable-encryption targets
Are you sure you want to disable encryption? (y/n):
Enter passphrase:
Encryption disabled

$ tuf enable-encryption targets
Enter passphrase:
Repeat passphrase:
Encryption enabled
```

WDYT?

**Comment by titanous** [comment]
SGTM

**Comment by lmars** [comment]
Closing in favour of #60
