### ISSUE TITLE
tuf-client get increases the size of the tuf.db (exponentially?)

### ISSUE THREAD

**Issue by philiplb** [flynn/go-tuf#93]
Hi,

this is how I check for new versions of Flynn:

Initially:

```bash
tuf-client init https://dl.flynn.io/tuf <<< '[{"keytype":"ed25519","keyval":{"public":"6cfda23aa48f530aebd5b9c01030d06d02f25876b5508d681675270027af4731"}}]'
```

and then for the checks for nightly and stable:

```bash
tuf-client get https://dl.flynn.io/tuf /channels/nightly
tuf-client get https://dl.flynn.io/tuf /channels/stable
```

Every time I execute the checks, the local tuf.db grows big times.

Call nr:

1. 31MB
2. 122M
3. 489M
4. 1.9G

etc..

**Comment by lmars** [comment]
@philiplb the ever increasing size is due to how Flynn is using go-tuf, rather than this being an issue with go-tuf itself, so closing this in favour of https://github.com/flynn/flynn/issues/2397
